@url = https://restapi-1-bn4u.onrender.com/api/v1

#@url = http://localhost:3000/api/v1
'
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibWlrZUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTA2MDU0ODUsImV4cCI6MTc1MDYwNjM4NX0.DYNFqj9yqhkilAQRa-qPRbMMRDlTck-odKcrrAnJEfQ
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibWlrZUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTA2MDU0ODUsImV4cCI6MTc1MTIxMDI4NX0.jPNEKoNSEeJmvcwqDVkjNbSbFGhf2yJU5hcDLJzsAGw

@useraccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoia2lwcm9wQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ5NTAxNDM3LCJleHAiOjE3NDk1MDIzMzd9.EAepyksiISalIsTjZYadHIhGMNDAOkwnaXQrQl3SGsg
@userrefreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoia2lwcm9wQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ5NTAxNDM3LCJleHAiOjE3NTAxMDYyMzd9.QFext7YQhdFhf0uHF_VlD7lsaRlF2VGIsOkXyephBNY

@guestaccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI4LCJlbWFpbCI6Im1rQGdtYWlsLmNvbSIsInJvbGUiOiJndWVzdCIsImlhdCI6MTc0OTU4ODU1NSwiZXhwIjoxNzQ5NTg5NDU1fQ.1G1j9EmUd-GrQ1XJoMxwg4-HeUZE0MSrRLu2WpL_-ZU
@guestrefreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI4LCJlbWFpbCI6Im1rQGdtYWlsLmNvbSIsInJvbGUiOiJndWVzdCIsImlhdCI6MTc0OTU4ODU1NSwiZXhwIjoxNzUwMTkzMzU1fQ.xON4gjrr_jTTXBYdj39kIjd9EhPDHs-EoX6ZexFwJ08

###
//admin
POST {{ url}}/auth/signin
Content-Type: application/json

{
  "email": "mike@gmail.com",
  "password": "password"
}

###
//user
POST {{ url}}/auth/signin
Content-Type: application/json

{
  "email": "kiprop@gmail.com",
  "password": "password"
}

###
//guest
POST {{ url}}/auth/signin
Content-Type: application/json

{
  "email": "mk@gmail.com",
  "password": "password"
}

###
GET  {{ url}}/auth/signout/1


###
GET  {{ url}}/auth/refresh?id=1
Authorization: Bearer {{refreshToken}}


###
POST {{url}}/seed
Authorization: Bearer {{accessToken}}

###
GET {{url}}/profiles
Authorization: Bearer {{accessToken}}

###
GET {{url}}/profiles


###
GET {{url}}/profiles
Authorization: Bearer {{useraccessToken}}

###
GET {{url}}/profiles
Authorization: Bearer {{guestaccessToken}}

###
GET {{url}}/profiles?email=mike@gmail.com
Authorization: Bearer {{accessToken}}

###
GET {{url}}/profiles/1
Authorization: Bearer {{accessToken}}

###
POST {{url}}/profiles
Content-Type: application/json

{
  "first_name": "Mike",
  "last_name":"Kiprop",
  "phone_number":"0733031821",
  "email":"mike@gmail.com",
  "password":"password",
  "role":"admin"
}

###
POST {{url}}/profiles
Content-Type: application/json

{
  "first_name": "Mike",
  "last_name":"Kiprop",
  "phone_number":"0733031821",
  "email":"kiprop@gmail.com",
  "password":"password",
  "role":"user"
}

###
POST {{url}}/profiles
Content-Type: application/json

{
  "first_name": "Mike",
  "last_name":"Kiprop",
  "phone_number":"0733031821",
  "email":"mikealwanga97@gmail.com",
  "password":"password",
  "role":"guest"
}

###
PATCH {{url}}/profiles/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "first_name":"mike"
}

###
DELETE {{url}}/profiles/1



###
GET {{url}}/admins
Authorization: Bearer {{accessToken}}

###
GET {{url}}/admins?email=mike@gmail.com

###
POST {{url}}/admins
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "username": "admin1",
  "lastlogin":"2025-04-04",
  "adminprofileid":1
}

###
GET {{url}}/admins/1

###
DELETE {{url}}/admins/1

###
GET {{url}}/users
Authorization: Bearer {{accessToken}}

###
GET {{url}}/users?email=mike@gmail.com

###
POST {{url}}/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "username": "mike",
  "lastlogin":"2025-04-04",
  "userprofileid":2
}

###
GET {{url}}/users/1

###
DELETE {{url}}/users/1


###
GET {{url}}/registrations
Authorization: Bearer {{accessToken}}


###
GET {{url}}/registrations/2


###
POST {{url}}/registrations
Content-Type: application/json

{
  "user_id": 1,
  "room_id":1,
  "course_id":1,
  "registration_date":"2025-04-04"
}



###
GET {{url}}/rooms
Authorization: Bearer {{accessToken}}

###
GET {{url}}/rooms?search=single

###
GET {{url}}/rooms/2


###
POST {{url}}/rooms
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "room_number": 3,
  "seaters":2,
  "fee":10000,
  "room_type":"Bed-sitter"
}


###
GET {{url}}/roombookings
Authorization: Bearer {{accessToken}}


###
GET {{url}}/roombookings/2
Authorization: Bearer {{accessToken}}


###
POST {{url}}/roombookings
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "user_id": 1,
  "room_id":1
}

###
GET {{url}}/userfeedbacks
Authorization: Bearer {{accessToken}}


###
GET {{url}}/userfeedbacks/2


###
POST {{url}}/userfeedbacks
Content-Type: application/json

{
  "user_id": 2,
  "feedack_text":"The room is big",
  "rating":3

}

###
GET {{url}}/complaints
Authorization: Bearer {{guestaccessToken}}


###
GET {{url}}/complaints/2


###
POST {{url}}/complaints
Content-Type: application/json

{
  "user_id": 2,
  "complaint_text":"The room  is  dirty",
  "status":"resolved"
}

###
GET {{url}}/useraccess


###
GET {{url}}/useraccess/2


###
POST {{url}}/useraccess
Content-Type: application/json

{
  "user_id": 2
}

###
GET {{url}}/courses

###
GET {{url}}/courses?search=it

###
GET {{url}}/courses/1


###
POST {{url}}/courses
Content-Type: application/json

{
  "course_name": "IT",
  "course_duration":"2yrs",
  "course_fee":50000
}



