

services:
  hostel-sys-db:
    image: postgres:15-alpine
    container_name: hostel-sys-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: hostel-system
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
  redis:
    image: redis:8.0-alpine
    container_name: hostel-sys-redis
    restart: unless-stopped
    command: ["redis-server","--requirepass","${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app-network

volumes:
  pgdata:
    name: hostel-sys-db-data
    driver: local
  redisdata:
    name: hostel-sys-redis-data
    driver: local

networks:
  app-network:
    driver: bridge



